# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20170623_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b3a15b84-3829-44ca-af8d-0fd9eadf45de'), primary_key=True, serialize=False, unique=True),
        ),
    ]
