# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20170623_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='uuid',
            field=models.UUIDField(default='', unique=True),
        ),
    ]
